GestionDeStockCusHabitat/Models/Sortie.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace GestionDeStockCusHabitat.Models
{
    public class Sortie
    {
        public int Id { get; set; }
        [Required][Display(Name = "Nom de l'article")]
        public String NomArticle { get; set; }
        [Required][Display(Name = "Catégorie")]
        public String Categorie { get; set; }
        [Required][Display(Name = "Quantité")]
        public int QteArticle { get; set; }
        public DateTime DateTime { get; set; }
        [Required][Display(Name = "Client")]
        public int ClientId { get; set; }
    }
}

GestionDeStockCusHabitat/Controllers/SortieController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using GestionDeStockCusHabitat.Models;
using GestionDeStockCusHabitat.ViewModel;

namespace GestionDeStockCusHabitat.Controllers
{
    [Authorize]
    public class SortieController : Controller
    {
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [Route("sortie")]
        public ActionResult Sortie()
        {
            using (var dbcontext = new ApplicationDbContext())
            {
                var model = new SortieViewModel {Sorties = dbcontext.Sorties.ToList()};
                return View(model);
            }

        }

        /// <summary>
        /// Route retournant la vue du formulaire de sortie
        /// </summary>
        /// <returns></returns>
        [Route("sortie/sortiearticle")]
        public ActionResult SortieArticle()
        {
            var dbContext = new ApplicationDbContext();
            var model = new SortieViewModel
            {
                ArticleList = new SelectList(dbContext.Articles.Select(c => c.NomArticle), "NomArticle"),
                ClientList = new SelectList(dbContext.Clients.Select(c => new {c.Nom, c.Prenom}))
            };
            
            return View(model);
        }

        public ActionResult SortirUnArticle(Sortie sortie)
        {
            using (var dbContext = new ApplicationDbContext())
            {
                sortie.Categorie = dbContext.Articles
                    .Where(a => a.NomArticle == sortie.NomArticle)
                    .Select(a => a.NomArticle).Single();
                sortie.DateTime = DateTime.Now;
                dbContext.Sorties.Add(sortie);
                var articleMisAJour = dbContext.Articles.Where(a => a.NomArticle == sortie.NomArticle).Select(a => a).Single();
                articleMisAJour.QteArticle = articleMisAJour.QteArticle - sortie.QteArticle;

                dbContext.SaveChanges();
                return RedirectToAction("Entree","Entree");
            }
        }
    }
}

GestionDeStockCusHabitat/Views/Sortie/Sortie.cshtml
@model GestionDeStockCusHabitat.ViewModel.SortieViewModel

@{
    ViewBag.Title = "Les sorties";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Les Sorties</h2>

@if (!Model.Sorties.Any())
{
    <p>Aucun article n'a été sortie</p>
}
else
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Nom de l'article</th>
                <th>Quantité</th>
                <th>Catégorie</th>
                <th>Heure et date de sortie</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var sorties in Model.Sorties)
            {
                <tr>
                    <td>@sorties.NomArticle</td>
                    <td>@sorties.QteArticle</td>
                    <td>@sorties.Categorie</td>
                    <td>@sorties.DateTime.ToShortTimeString() - @sorties.DateTime.ToShortDateString()</td>
                </tr>
            }
        </tbody>
    </table>
}
@Html.ActionLink("Ajouter une nouvelle sortie", "SortieArticle", "Sortie", new { @class = "btn btn-primary" })

GestionDeStockCusHabitat/Views/Sortie/SortieArticle.cshtml
@model GestionDeStockCusHabitat.ViewModel.SortieViewModel
@using GestionDeStockCusHabitat.Models

@{
    ViewBag.Title = "Sortie d'un article";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sortie d'un article</h2>
@using (Html.BeginForm("SortirUnArticle", "Sortie"))
{
    <div class="form-group">
        @Html.LabelFor(a => a.NomArticle)
        @Html.DropDownListFor(a => a.NomArticle, Model.ArticleList, new {@class = "form-control"})
    </div>
    <div class="form-group">
        @Html.LabelFor(a => a.QteArticle)
        @Html.TextBoxFor(a => a.QteArticle, new { @class = "form-control", pattern = @"\d{*}" })
    </div>
    <div class="form-group">
        @Html.LabelFor(a => a.ClientList)
        @Html.DropDownListFor(a => a.ClientId, Model.ClientList, new {@class = "form-control"})
    </div>
    <div class="form-group">
    </div>
    <button type="submit" class="btn btn-primary">Valider la sortie</button>
}